#############################################################################
# Makefile for building: MassPixel
# Generated by qmake (2.01a) (Qt 4.8.4) on: Tue Mar 12 16:52:40 2013
# Project:  MassPixel.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile MassPixel.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = core.cpp \
		main.cpp \
		massmain.cpp moc_core.cpp \
		moc_massmain.cpp \
		qrc_zasoby.cpp
OBJECTS       = core.o \
		main.o \
		massmain.o \
		moc_core.o \
		moc_massmain.o \
		qrc_zasoby.o
DIST          = /usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt4/mkspecs/common/g++-base.conf \
		/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		MassPixel.pro
QMAKE_TARGET  = MassPixel
DESTDIR       = 
TARGET        = MassPixel

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_massmain.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MassPixel.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt4/mkspecs/common/g++-base.conf \
		/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile MassPixel.pro
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/common/gcc-base.conf:
/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt4/mkspecs/common/g++-base.conf:
/usr/lib/qt4/mkspecs/common/g++-unix.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile MassPixel.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MassPixel1.0.0 || $(MKDIR) .tmp/MassPixel1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MassPixel1.0.0/ && $(COPY_FILE) --parents core.h massmain.h .tmp/MassPixel1.0.0/ && $(COPY_FILE) --parents zasoby.qrc .tmp/MassPixel1.0.0/ && $(COPY_FILE) --parents core.cpp main.cpp massmain.cpp .tmp/MassPixel1.0.0/ && $(COPY_FILE) --parents massmain.ui .tmp/MassPixel1.0.0/ && $(COPY_FILE) --parents lang/pl_PL.ts lang/en_GB.ts lang/en_US.ts .tmp/MassPixel1.0.0/ && (cd `dirname .tmp/MassPixel1.0.0` && $(TAR) MassPixel1.0.0.tar MassPixel1.0.0 && $(COMPRESS) MassPixel1.0.0.tar) && $(MOVE) `dirname .tmp/MassPixel1.0.0`/MassPixel1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MassPixel1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_core.cpp moc_massmain.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_core.cpp moc_massmain.cpp
moc_core.cpp: core.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) core.h -o moc_core.cpp

moc_massmain.cpp: core.h \
		massmain.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) massmain.h -o moc_massmain.cpp

compiler_rcc_make_all: qrc_zasoby.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_zasoby.cpp
qrc_zasoby.cpp: zasoby.qrc \
		icon.png
	/usr/lib/qt4/bin/rcc -name zasoby zasoby.qrc -o qrc_zasoby.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_massmain.h
compiler_uic_clean:
	-$(DEL_FILE) ui_massmain.h
ui_massmain.h: massmain.ui
	/usr/lib/qt4/bin/uic massmain.ui -o ui_massmain.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

core.o: core.cpp core.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o core.o core.cpp

main.o: main.cpp massmain.h \
		core.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

massmain.o: massmain.cpp massmain.h \
		core.h \
		ui_massmain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o massmain.o massmain.cpp

moc_core.o: moc_core.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_core.o moc_core.cpp

moc_massmain.o: moc_massmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_massmain.o moc_massmain.cpp

qrc_zasoby.o: qrc_zasoby.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_zasoby.o qrc_zasoby.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

