######################################################################
# Automatically generated by qmake (2.01a) sob. mar 2 11:27:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . output
INCLUDEPATH += .

# Input
HEADERS += core.h massmain.h
FORMS += massmain.ui
SOURCES += core.cpp main.cpp massmain.cpp
RESOURCES += zasoby.qrc
TRANSLATIONS += lang/pl_PL.ts \
lang/en_US.ts \
lang/en_GB.ts
